version: 2.1
executors:
  build-executor:
    docker:
      - image: cimg/node:lts

orbs:
  node: circleci/node@4.7.0

jobs:
  build-check:
    environment:
      # TOKEN: This ENV variable is defined within Circle CI.
      PROD_CHANNEL_ACTIVITY_ALL: 859521842317754369
      METADATA_REFRESH_INTERVAL_MINUTES: 60
      RANDOM_ART_INTERVAL_MINUTES: 20
      GOOGLE_AUTH_DETAILS: '{}'
    executor: build-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Run application
          command: |
            timeout 2m yarn start || ( [[ $? -eq 124 ]] && echo "WARNING: Timeout reached, but that's OK" )
      - run:
          name: Run Tests
          command: yarn test

workflows:
  build-workflow:
    jobs:
      - build-check
